services:
  - type: web
    name: criarIA-frontend
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: VITE_API_URL
        value: https://criaria.onrender.com/api
